"use client";
import type { TBAEliminationAlliance, TBAEventTeamStatuses } from "@/lib/tba/types";
import { useMemo, useState } from "react";
export default function EventStatsSideBar({ teamStatuses = {}, playoffAlliances = [] }: { teamStatuses?: TBAEventTeamStatuses; playoffAlliances?: TBAEliminationAlliance[] }) {
  const [mode, setMode] = useState("rankings");
  const rankings = useMemo(() => Object.entries(teamStatuses).map(([key, status]) => ({ key, rank: status?.qual?.ranking?.rank ?? Infinity, record: status?.qual?.ranking?.record ?? {} })).sort((a,b)=>a.rank-b.rank), [teamStatuses]);
  return <div className="flex h-full flex-col bg-neutral-950"><div className="flex border-b border-white/10 p-2"><button onClick={()=>setMode("rankings")} className={`flex-1 rounded-lg px-3 py-2 text-xs font-semibold ${mode==="rankings"?"bg-white text-black":"text-neutral-500 hover:bg-white/5"}`}>Rankings</button>{playoffAlliances.length>0&&<button onClick={()=>setMode("alliances")} className={`flex-1 rounded-lg px-3 py-2 text-xs font-semibold ${mode==="alliances"?"bg-white text-black":"text-neutral-500 hover:bg-white/5"}`}>Alliances</button>}</div><div className="min-h-0 flex-1 overflow-y-auto p-2">{mode==="rankings"?rankings.map((team)=><div key={team.key} className="mb-1 flex items-center gap-3 rounded-lg bg-white/[.04] px-3 py-2"><span className="w-7 text-center font-mono text-xs font-bold">{Number.isFinite(team.rank)?team.rank:"–"}</span><span className="flex-1 text-sm">{String(team.key).replace(/^frc/,'')}</span><span className="font-mono text-[10px] text-neutral-500">{team.record.wins??0}-{team.record.losses??0}{team.record.ties?`-${team.record.ties}`:""}</span></div>):playoffAlliances.map((a,i)=><div key={a.name||i} className="mb-2 rounded-lg border border-white/10 bg-white/[.04] p-3"><div className="text-xs font-semibold">{a.name||`Alliance ${i+1}`}</div><div className="mt-2 flex gap-2">{(a.picks||[]).map(t=><span key={t} className="rounded bg-white/5 px-2 py-1 font-mono text-[10px]">{String(t).replace(/^frc/,'')}</span>)}</div></div>)}{mode==="rankings"&&!rankings.length&&<Empty text="Rankings are not available yet."/>}{mode==="alliances"&&!playoffAlliances.length&&<Empty text="Alliance data is not available yet."/>}</div></div>;
}
function Empty({text}: { text: string }){return <div className="p-8 text-center text-xs text-neutral-600">{text}</div>}
